language: go
go:
- master
env:
  matrix:
  - GO111MODULE=on
  global:
    secure: sCd5znxehlM/O97ueSuJUkNkOdWvMDWr1qb6nqnYUFlhym3W7VjD35Js78HOLJpmIhkmWgGfAmwV4hEKWMKMSCXkXnd6jwapBxoIMivfAdL3XBxIv5QLSQ197HcaiZborBHBk2XzU/2/XYZHDttn0Z7ITWE8d64gJrGShoK/pITgpkKLK2WJaC177u9ZypDOqcJeCr2ahvLIClvR6YFL2deRKuKlFGAqVDeftvnD3UFbxXx6+nxhw4RIdsn/JL5yVLdscGcGu4Ox3B2Mcwf3wDHBj5PahskPlXeOj49OTJhr4QJcE267I1AHa8fyQCqOB7a5CT8rHwxp/dwLpgq20Fv8YWHRLmnEcM39O8qQ93l265mpFqgrydLHuw3s4fJ1CjkrGOv4mn9SImE4FVpI3juYLhwvf1Tp66uH/+Sxj28fNOt4SgetkZx+SfLEggSbcwXkfSFeAVD/kuCxqZMB5z/ySZ4Mnztml+Ho39SzNbJmuG2NTQsRLmZG+Fr4pEa0nCgWhPA7jegYWxrmB455gElqFVSe8GnBTHkLIpuWN1NP6pnp7HyXauOP0tzgEmTihzm20cABTgda1NVSVEHlmdN5ocBUjBem7cDQhMDCUWHImZXTIQ/scxpYU0dWz4oGaSGM0QjE28lw5t+qrZezKOlQAkhxJkhfoqAHhHkhngQ=
script:
- go vet ./...
- go test -v -covermode=atomic -coverpkg ./commenter/... -coverprofile coverage.txt ./...
